apiVersion: v1
kind: Service
metadata:
 name: mysql-media
 labels:
   app: mysql-media
spec:
 type: ClusterIP
 selector:
   app: mysql-media
 ports:
   - port: 3306
     protocol: TCP
 clusterIP: "None"
